//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

public class NewMatrixPanel extends JPanel {
    private JTextField A;
    private JTextField F;
    private JTextField E;
    private JTextField B;
    private JTextField D;
    private JTextField C;
    private JLabel Fbis;
    private JLabel Ebis;
    private JLabel Dbis;

    public NewMatrixPanel() {
        //construct components
        A = new JTextField (5);
        F = new JTextField (5);
        E = new JTextField (5);
        B = new JTextField (5);
        D = new JTextField (5);
        C = new JTextField (5);
        Fbis = new JLabel ("         -F");
        Ebis = new JLabel ("         -E");
        Dbis = new JLabel ("         -D");

        //adjust size and set layout
        setPreferredSize (new Dimension (258, 188));
        setLayout (null);

        //add components
        add (A);
        add (F);
        add (E);
        add (B);
        add (D);
        add (C);
        add (Fbis);
        add (Ebis);
        add (Dbis);

        //set component bounds (only needed by Absolute Positioning)
        A.setBounds (30, 20, 60, 35);
        F.setBounds (100, 20, 60, 35);
        E.setBounds (175, 20, 60, 35);
        B.setBounds (100, 75, 60, 35);
        D.setBounds (175, 75, 60, 35);
        C.setBounds (175, 125, 60, 35);
        Fbis.setBounds (20, 75, 65, 35);
        Ebis.setBounds (20, 120, 70, 40);
        Dbis.setBounds (100, 125, 65, 35);
    }
}