//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.util.Map;
import javax.swing.*;

public class SolidPanel extends JPanel {
    private JLabel jcomp1;
    private JComboBox basisChoice;
    private JLabel jcomp3;
    private JTextField jcomp4;
    private JLabel jcomp5;
    private JTextField nameMatrix;
    private JLabel jcomp7;
    private JButton newMatrix;
    private JLabel jcomp9;
    private JTextField pointOfMatrix;

    public SolidPanel(UI ui, New window) {
        //construct preComponents
        String[] basisChoiceItems = {"item 1"};

        //construct components
        jcomp1 = new JLabel ("Basis : ");
        String[] items=new String[ui.basis.size()];
        int i=0;
        for (Map.Entry<String, Basis> entry : ui.basis.entrySet()) {
            String basisName = entry.getKey();
            Basis value = entry.getValue();
            items[i]=basisName;
            i++;
        }
        basisChoice = new JComboBox (items);
        jcomp3 = new JLabel ("Mass :");
        jcomp4 = new JTextField (5);
        jcomp5 = new JLabel ("Matrix :");
        nameMatrix = new JTextField (5);
        jcomp7 = new JLabel ("or");
        newMatrix = new JButton ("new");
        jcomp9 = new JLabel ("Point of Matrix :");
        pointOfMatrix = new JTextField (5);

        //adjust size and set layout
        setPreferredSize (new Dimension (294, 171));
        setLayout (null);

        //add components
        add (jcomp1);
        add (basisChoice);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (nameMatrix);
        add (jcomp7);
        add (newMatrix);
        add (jcomp9);
        add (pointOfMatrix);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (20, 25, 100, 25);
        basisChoice.setBounds (85, 25, 185, 25);
        jcomp3.setBounds (20, 60, 100, 25);
        jcomp4.setBounds (85, 60, 165, 25);
        jcomp5.setBounds (20, 95, 100, 25);
        nameMatrix.setBounds (85, 95, 70, 25);
        jcomp7.setBounds (165, 95, 50, 25);
        newMatrix.setBounds (190, 95, 75, 25);
        jcomp9.setBounds (20, 130, 100, 25);
        pointOfMatrix.setBounds (120, 130, 125, 25);
    }
}