//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

public class VariablesPanel extends JPanel {
    public JTextField variables;
    public JButton OK;
    public JLabel text;

    public VariablesPanel(UI ui, VariablesWindow window) {
        //construct components
        variables = new JTextField (5);
        OK = new JButton ("OK");
        OK.addActionListener(window);
        text = new JLabel ("Enter here the variables you wil use (separated with commas)");

        //adjust size and set layout
        setPreferredSize (new Dimension (528, 137));
        setLayout (null);

        //add components
        add (variables);
        add (OK);
        add (text);

        //set component bounds (only needed by Absolute Positioning)
        variables.setBounds (30, 55, 470, 30);
        OK.setBounds (200, 95, 100, 25);
        text.setBounds (30, 10, 360, 30);
    }
}